services:
  db:
    image: postgres:latest #14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
    environment:
      - WATCHPACK_POLLING=true #wazne
    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DJANGO_SETTINGS_MODULE=backend.settings
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    command: >
      sh -c "wait-for-it db:5432 --timeout=60 -- python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8000 backend.asgi:application"

  #sh -c "wait-for-it db:5432 --timeout=60 -- python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
  #sh -c "wait-for-it db:5432 --timeout=60 -- python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "8080:80"
    depends_on:
      - db
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"