# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/toolpad/v0.12.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Default page
  alias:
    - axOHi6G
  content:
    - component: Text
      name: text
      props:
        mode: text
        variant: h2
        value: Logowanie
      layout:
        horizontalAlign: center
        verticalAlign: center
    - component: TextField
      name: textField
      layout:
        horizontalAlign: center
        verticalAlign: center
      props:
        password: true
        label: Hasło
    - component: Button
      name: button
      layout:
        horizontalAlign: center
        verticalAlign: center
      props:
        content: Zaloguj
