# Generated by Django 5.1.3 on 2024-12-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='owner_role',
            field=models.CharField(choices=[('client', 'Client'), ('restaurateur', 'Restaurateur')], default='client', max_length=20),
        ),
    ]
