# Generated by Django 5.1.3 on 2024-12-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
    ]
