# Generated by Django 5.1.3 on 2025-01-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='allows_cash_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='allows_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='allows_online_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='allows_pickup',
            field=models.BooleanField(default=True),
        ),
    ]
