# Generated by Django 5.1.3 on 2025-01-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_restaurant_minimum_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_cities',
            field=models.ManyToManyField(blank=True, to='core.city'),
        ),
    ]
