# Generated by Django 5.1.3 on 2025-01-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_city_restaurant_delivery_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='allows_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
