# Generated by Django 5.1.3 on 2025-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
