# Generated by Django 5.1.3 on 2025-01-31 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_cartitem_options_remove_cartitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.order'),
        ),
    ]
