# Generated by Django 5.1.3 on 2025-02-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_chatmessage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
