# Generated by Django 5.1.3 on 2025-02-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('suspended', 'Suspended'), ('resumed', 'Resumed')], default='pending', max_length=20),
        ),
    ]
